import gameStore


def addGames(store):
    store.add_game(1, "The Witcher 3: Wild Hunt", 100, ["RPG", "Ação"])
    store.add_game(2, "Minecraft", 75, ["Sandbox", "Aventura"])
    store.add_game(3, "Grand Theft Auto V", 120, ["Ação", "Aventura"])
    store.add_game(4, "Stardew Valley", 40, ["Indie", "Simulação"])
    store.add_game(5, "Red Dead Redemption 2", 150, ["Ação", "Aventura"])
    store.add_game(6, "Hollow Knight", 50, ["Indie", "Plataforma"])
    store.add_game(7, "Celeste", 45, ["Indie", "Plataforma"])
    store.add_game(8, "Dark Souls III", 110, ["RPG", "Ação"])
    store.add_game(9, "Sekiro: Shadows Die Twice", 130, ["RPG", "Ação"])
    store.add_game(10, "Fortnite", 0, ["Battle Royale", "Ação"])
    store.add_game(11, "Apex Legends", 0, ["Battle Royale", "FPS"])
    store.add_game(12, "Overwatch 2", 80, ["FPS", "Ação"])
    store.add_game(13, "Valorant", 0, ["FPS", "Estratégia"])
    store.add_game(14, "Counter-Strike: Global Offensive", 0, ["FPS", "Estratégia"])
    store.add_game(15, "League of Legends", 0, ["MOBA", "Estratégia"])
    store.add_game(16, "Dota 2", 0, ["MOBA", "Estratégia"])
    store.add_game(
        17, "Age of Empires II: Definitive Edition", 100, ["Estratégia", "Simulação"]
    )
    store.add_game(18, "Civilization VI", 150, ["Estratégia", "Simulação"])
    store.add_game(19, "The Sims 4", 120, ["Simulação", "Casual"])
    store.add_game(20, "FIFA 23", 200, ["Esportes", "Casual"])
    store.add_game(21, "Rocket League", 0, ["Esportes", "Ação"])
    store.add_game(22, "Among Us", 20, ["Indie", "Party Game"])
    store.add_game(23, "Fall Guys", 0, ["Party Game", "Plataforma"])
    store.add_game(24, "Dead Cells", 60, ["Indie", "Roguelike"])
    store.add_game(25, "Hades", 90, ["Indie", "Roguelike"])
    store.add_game(26, "Disco Elysium", 130, ["RPG", "Indie"])
    store.add_game(27, "Slay the Spire", 80, ["Indie", "Cartas"])
    store.add_game(28, "Doom Eternal", 140, ["FPS", "Ação"])
    store.add_game(29, "Half-Life: Alyx", 180, ["FPS", "VR"])
    store.add_game(30, "Portal 2", 50, ["Puzzle", "Aventura"])
    store.add_game(31, "Limbo", 20, ["Puzzle", "Indie"])
    store.add_game(32, "Inside", 30, ["Puzzle", "Indie"])
    store.add_game(33, "Subnautica", 70, ["Aventura", "Simulação"])
    store.add_game(34, "No Man's Sky", 150, ["Aventura", "Simulação"])
    store.add_game(35, "Terraria", 40, ["Sandbox", "Aventura"])
    store.add_game(36, "Don't Starve", 45, ["Indie", "Sobrevivência"])
    store.add_game(37, "ARK: Survival Evolved", 100, ["Ação", "Sobrevivência"])
    store.add_game(38, "Rust", 120, ["Ação", "Sobrevivência"])
    store.add_game(39, "Phasmophobia", 70, ["Terror", "Indie"])
    store.add_game(40, "Outlast", 60, ["Terror", "Aventura"])
    store.add_game(41, "Resident Evil 4", 110, ["Terror", "Ação"])
    store.add_game(42, "Resident Evil Village", 160, ["Terror", "Ação"])
    store.add_game(43, "The Forest", 75, ["Terror", "Sobrevivência"])
    store.add_game(44, "Cyberpunk 2077", 170, ["RPG", "Ação"])
    store.add_game(45, "Mass Effect Legendary Edition", 200, ["RPG", "Ação"])
    store.add_game(46, "Bioshock Infinite", 80, ["FPS", "Aventura"])
    store.add_game(47, "Borderlands 3", 130, ["FPS", "Ação"])
    store.add_game(48, "Destiny 2", 0, ["FPS", "RPG"])
    store.add_game(49, "Assassin's Creed Valhalla", 200, ["Ação", "Aventura"])
    store.add_game(50, "Ori and the Will of the Wisps", 90, ["Indie", "Plataforma"])
